apiVersion: v1
kind: Service
metadata:
  name: tenant-service
spec:
  type: NodePort
  selector:
    app: tenant
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30004