apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: marketplace-gateway
  namespace: kong
spec:
  gatewayClassName: marketplace-gateway-class
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All