apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: marketplace-gateway
spec:
  gatewayClassName: marketplace-class
  listeners:
  - name: http
    protocol: HTTP
    port: 80
  - name: https
    protocol: HTTPS
    port: 443