apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: marketplace-httproute
  annotations:
    konghq.com/strip-path: 'true'
spec:
  parentRefs:
  - name: marketplace-gateway
    namespace: 'default'
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /service-auth
      backendRefs:
      - name: auth-service
        kind: Service
        port: 80
    - matches:
      - path:
          type: PathPrefix
          value: /service-order
      backendRefs:
      - name: order-service
        kind: Service
        port: 80
    - matches:
      - path:
          type: PathPrefix
          value: /service-product
      backendRefs:
      - name: product-service
        kind: Service
        port: 80
    - matches:
      - path:
          type: PathPrefix
          value: /service-tenant
      backendRefs:
      - name: tenant-service
        kind: Service
        port: 80
    - matches:
      - path:
          type: PathPrefix
          value: /service-wishlist
      backendRefs:
      - name: wishlist-service
        kind: Service
        port: 80