apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: marketplace-httproute
  annotations:
    konghq.com/strip-path: 'true'
spec:
  parentRefs:
  - name: marketplace-gateway
  - namespace: kong
  hostnames:
  - "34.232.30.223"
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /auth
      backendRefs:
      - name: auth-service
        kind: Service
        port: 80
    - matches:
      - path:
          type: PathPrefix
          value: /order
      backendRefs:
      - name: order-service
        kind: Service
        port: 80
    - matches:
      - path:
          type: PathPrefix
          value: /product
      backendRefs:
      - name: product-service
        kind: Service
        port: 80
    - matches:
      - path:
          type: PathPrefix
          value: /tenant
      backendRefs:
      - name: tenant-service
        kind: Service
        port: 80
    - matches:
      - path:
          type: PathPrefix
          value: /wishlist
      backendRefs:
      - name: wishlist-service
        kind: Service
        port: 80