#controller:
#  ingressController:
#    env:
#      LOG_LEVEL: trace
#      dump_config: true

apiVersion: gateway.networking.k8s.io/v1
gateway:
  admin:
    http:
      enabled: true
  proxy:
    type: NodePort
    http:
      enabled: true
      nodePort: 32001
    tls:
      enabled: false

#  ingressController:
#    env:
#      LOG_LEVEL: trace