apiVersion: v1
kind: Service
metadata:
  name: product-db-service
spec:
  type: NodePort
  selector:
    app: product-db
  ports:
    - name: default
      port: 5432
      targetPort: 5432
      nodePort: 30603