services:
  service-product:
    build: .
    ports:
      - "8883:8000"
    environment:
      # THIS ONE BELOW IS VERY IMPORTANT
      - TENANT_ID=9f4a0c73-f10b-4b1e-bdd4-599dfd9d3217
      # 
      - ADMIN_TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - ADMIN_JWT_SECRET=admin_auth_ms_jwt_secret
      - AUTH_MS_URL=http://host.docker.internal:8881
      - ORDER_MS_URL=http://host.docker.internal:8882
      - PRODUCT_MS_URL=http://host.docker.internal:8883
      - TENANT_MS_URL=http://host.docker.internal:8884
      - WISHLIST_MS_URL=http://host.docker.internal:8885
      - DB_HOST=db-product
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=marketplace
    depends_on:
      - db-product

  db-product:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5443:5432"
    volumes:
      - product-data:/var/lib/postgresql/data

volumes:
  product-data: