apiVersion: v1
kind: Secret
metadata:
  name: product-secrets
type: Opaque
data:
  JWT_SECRET: YXV0aF9tc19qd3Rfc2VjcmV0 # echo -n "auth_ms_jwt_secret" | base64
  ADMIN_JWT_SECRET: YWRtaW5fYXV0aF9tc19qd3Rfc2VjcmV0 # echo -n "admin_auth_ms_jwt_secret" | base64
  DB_PASSWORD: cG9zdGdyZXM= # echo -n "postgres" | base64