apiVersion: v1
kind: PersistentVolume
metadata:
  name: tenant-db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/tenant-postgresql