apiVersion: v1
kind: Service
metadata:
  name: wishlist-db-service
spec:
  type: NodePort
  selector:
    app: wishlist-db
  ports:
    - name: default
      port: 5432
      targetPort: 5432
      nodePort: 30605